# Generated by Django 2.2.15 on 2021-06-09 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='ursername',
            new_name='username',
        ),
    ]
