# Generated by Django 2.2.15 on 2021-07-14 01:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_chat', '0002_alter_publicchatroom_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicchatroom',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publicchatroom',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='users who are connected to chat room.', null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicroomchatmessage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
