# Generated by Django 2.2.15 on 2021-08-11 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritemovies',
            options={'managed': False},
        ),
    ]
