# Generated by Django 2.2.15 on 2021-08-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210811_0933'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='favoritemovies',
            table='favorite_movies',
        ),
    ]
