# Generated by Django 2.2.24 on 2021-07-25 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210725_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritemovies',
            options={},
        ),
    ]
