# Generated by Django 2.2.24 on 2021-07-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20210726_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritemovies',
            options={'managed': False},
        ),
    ]
